// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  experimental: {
    extensions: true,
  },
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI-only connection (migrate/studio/introspect). This install's
    // `Datasource` type has no `directUrl`, so the unpooled Neon URL goes
    // here; the app's runtime PrismaNeon adapter (lib/db.ts) uses the
    // pooled DATABASE_URL instead.
    url: env("DIRECT_URL"),
  },
});
